### PR TITLE
Report distribution metric to datadog instead of gauge

### PR DESCRIPTION
**Pull request by stephenhyde**
https://github.com/DataDog/opencensus-go-exporter-datadog/issues/17

### CODE REVIEW

**Comment by stephenhyde** [comment]
Interesting. The stats_test file passes locally.

**Comment by stephenhyde** [comment]
I read through https://github.com/DataDog/opencensus-go-exporter-datadog/pull/1 to why we do it as Gauge. We may be duplicating work but we can not make use of distribution metrics in Datadog.

**Comment by stephenhyde** [comment]
@AlexandreYang any idea why I am failing three test cases in stats_test.go? I ran the same command circleci running locally and I pass.

**Comment by AlexandreYang** [comment]
Hi @stephenhyde, not sure why but will try to have a look at this this week.

Related to this PR, please have a look at this (sending bucket data as DogStatsD distribution type is likely not the right way):
https://github.com/DataDog/opencensus-go-exporter-datadog/issues/17#issuecomment-641523505

**Comment by stephenhyde** [comment]
@AlexandreYang you available to look at it this week?

**Comment by AlexandreYang** [comment]
Hi @stephenhyde , sorry for the late reply. 

DistributionData from OpenCensus is more related to the concept of [Histogram type in Datadog](https://docs.datadoghq.com/developers/metrics/types/?tab=histogram), not the [Distribution type in Datadog](https://docs.datadoghq.com/developers/metrics/types/?tab=distribution#metric-types).

Hence, I think it's not suitable to send min/max/count/avg/squared_dev_sum metrics as distribution metrics.

But as commented on the other PR (https://github.com/DataDog/opencensus-go-exporter-datadog/issues/17#issuecomment-641523505), buckets can be used as input for distribution metrics.

**Comment by stephenhyde** [comment]
Hi @AlexandreYang, 

I am not sure how to proceed. I did throw out all the opencensus aggregation so we could keep the simple metric but I can see why you would think Histogram. My concern is thou, if you use opencensus and golang you will never be able to make use of the distribution feature in github. It too expensive to have guage metrics constantly reporting to datadog (Especially if you have service wide metrics that have a crap ton of unique metrics). Datadog has the ability to whitelist tags and ultimately drive down the cost of your unique tag limit. 

Is the only answer here to move to ddtrace directly? Do we throw out the opencensus data as we are using a datadog exporter. Will Histogram even help with the cardinality of unique metrics with tags? What do you suggest.

**Comment by AlexandreYang** [comment]
If the issue is about having too many contexts (unique combination of metric name + tags). You can possibly reduce the number of tags that create a lot of contexts/cardinality, if that's feasible in your context.

**Comment by stephenhyde** [comment]
Which is what I have been doing but when you use things like ocgrpc or ochttp across your microservices you are going to be screwed. The intention of those metrics were to be distribution. 

My main concern is that when using a golang datadog exporter with open census there is no way to make use of distribution metrics outside calling dd tracer directly and not using opencensus.

**Pull request closed without merging**
