### PR TITLE
Convert project to go modules based project

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by marwan-at-work** [comment]
This PR should be seriously considered as this library uses 5 dependencies yet pins none of their versions. If Go Modules is not being considered, then the underlying dependency versions should be pinned in some other way.

**Comment by gbbr** [comment]
I guess we could do it. The PR would need an update though.

**Comment by sargun** [comment]
We ended up forking the project to make headway. Feel free to edit this PR, or close it.

**Comment by marwan-at-work** [comment]
Thanks @sargun 

@gbbr I will open another PR as I don't have access to edit this one (https://github.com/DataDog/opencensus-go-exporter-datadog/pull/63)

Feel free to close this

**Pull request closed without merging**
